import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import { ToDoProvider } from '@/contexts/todo-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <ToDoProvider>
        <body className="bg-[#011F33]">
          <Header />
          <div className="mx-auto bg-[#011F33] min-h-full w-full max-w-[900px] ">
            {children}
          </div>
        </body>
      </ToDoProvider>
    </html>
  )
}
